testing reusable workflow

diff --git a/.github/workflows/run_ops.yml b/.github/workflows/run_ops.yml
--- a/.github/workflows/run_ops.yml
+++ b/.github/workflows/run_ops.yml
@@ -75,146 +75,146 @@ jobs:
   # In the context of a testing environment, where updates to these
   # scripts is part of the development workflow, the toolkit needs
   # to be compiled on every run
-#  toolkit:
-#    needs: [envs]
-#    runs-on: ubuntu-latest
-#    env:
-#      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
-#      TOOLKIT_IMAGE: ${{ needs.envs.outputs.TOOLKIT_IMAGE }}
-#      SHA: sha-${{ github.sha }}
-#    outputs:
-#      image: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.image_name }}
-#    steps:
-#      - name: Get image name lowercase
-#        id: 'lowercase'
-#        run: |
-#          IMAGE_NAME_LOWER=$(echo $TOOLKIT_IMAGE | tr '[:upper:]' '[:lower:]')
-#          echo "image_name=$IMAGE_NAME_LOWER" >> $GITHUB_OUTPUT
-#      - name: Check out source code
-#        uses: actions/checkout@master # change to main
-#        with:
-#          ref: ${{ env.BRANCH_REF }}
-#      - name: Log in to the Container registry
-#        uses: docker/login-action@master
-#        with:
-#          registry: ${{ env.REGISTRY }}
-#          username: ${{ github.actor }}
-#          password: ${{ secrets.GITHUB_TOKEN }}
-#      - name: Check if image with sha tag already exists
-#        id: check-image
-#        run: |
-#          set -e
-#          SHA_IMAGE=$(docker images -q ${REGISTRY}/${{ steps.lowercase.outputs.image_name }}:${SHA} || true)
-#          if [ -z "$SHA_IMAGE" ]; then
-#            echo "image_exists=false" >> $GITHUB_OUTPUT
-#          else
-#            echo "image_exists=true" >> $GITHUB_OUTPUT
-#          fi
-#      - name: Extract metadata (tags, labels) for Docker
-#        id: meta
-#        uses: docker/metadata-action@master
-#        with:
-#          images: ${{ env.REGISTRY }}/${{ env.TOOLKIT_IMAGE }}
-#          tags: |
-#            latest
-#            ${{ env.SHA }}
-#      - name: Build and push
-#        uses: docker/build-push-action@master
-#        with:
-#          context: toolkit
-#          push: true
-#          tags: ${{ steps.meta.outputs.tags }}
-#          labels: ${{ steps.meta.outputs.labels }}
-#
-#  # Download environmental data used for model boundaries and surface forcing.
-#  # This job is retried if it fails, since the failure can be due to upstream errors
-#  # These downloads are used to create forcing files that are fed as input to the CROCO model
-#  # => marine.copernicus.eu: This is ocean data that forms the lateral boundaries of our model run
-#  # => ncei.noaa.gov: This is atmospheric data used to create surface boundary conditions for our model run
-#  download-global-data:
-#    needs: [toolkit, envs]
-#    runs-on: somisana
-#    env:
-#      GLOBAL_DIR: ${{ needs.envs.outputs.GLOBAL_DIR }}
-#      MODEL_RUN_DATE: ${{ needs.envs.outputs.MODEL_RUN_DATE }}
-#      SHA: sha-${{ github.sha }}
-#      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
-#    steps:
-#      - name: Clean /home/runner/somisana/global_data/ # haven't tested this part of the job yet!
-#        run: >-
-#          find \
-#            /home/runner/somisana/global_data/* \
-#            -maxdepth 0 \
-#            -type d \
-#            -ctime +5 \
-#            -exec \
-#              rm \
-#                -rf {} \; 
-#      - name: Configure no. retries
-#        id: retries
-#        run: |
-#          if [ "$BRANCH_REF" = "stable" ]
-#          then
-#            echo "RETRIES=30" >> $GITHUB_OUTPUT
-#          else
-#            echo "RETRIES=1" >> $GITHUB_OUTPUT
-#          fi
-#      - name: Source ~/.bashrc (for NVM - required for non-interactive shells)
-#        continue-on-error: true # Maybe Node.js exists anyway
-#        run: |
-#          source ~/.bashrc
-#          nvm use 19.6.0
-#      - name: Create ${{ env.GLOBAL_DIR }} directory 
-#        run: |
-#          rm -rf ${{ env.GLOBAL_DIR }} 
-#          mkdir -p ${{ env.GLOBAL_DIR }} 
-#          chown -R :runners ${{ env.GLOBAL_DIR }} 
-#          chmod -R 774 ${{ env.GLOBAL_DIR }} 
-#      - name: Download GFS # NOTE - DON"T WRITE TO /tmp IN THE IMAGE - RATHER USE /tmp/somisana/blah. Zach had --workdir /tmp/somisana/current/forcing-inputs - we don't have the forcing inputs directory. Not sure this impacts us now that we write the .env file to the same directory as where the global data are downloaded instead of above - need to check this still works with the matlab step
-#        uses: nick-fields/retry@master 
-#        with:
-#          timeout_minutes: 30 # Script is considered failed if this limit is reached
-#          retry_wait_seconds: 300 # Wait 5 minutes and try again
-#          max_attempts: ${{ steps.retries.outputs.RETRIES }}
-#          retry_on: any
-#          warning_on_retry: true
-#          shell: bash
-#          continue_on_error: false
-#          on_retry_command: rm -f ${{ env.GLOBAL_DIR }}/*grb*
-#          command: >-
-#            docker run \
-#              --rm \
-#              -v ${{ env.GLOBAL_DIR }}/:/tmp/somisana/current \
-#              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
-#                download \
-#                  --provider gfs \
-#                  --workdir /tmp/somisana/current \ 
-#                  --matlab-env /tmp/somisana/current/.env \
-#                  --download-date ${{ env.MODEL_RUN_DATE }} \
-#                  --domain 22,31,-37,-31
-#      - name: Download Mercator
-#        uses: nick-fields/retry@master
-#        with:
-#          timeout_minutes: 30 # Script is considered failed if this limit is reached
-#          retry_wait_seconds: 300 # Wait 5 minutes and try again
-#          max_attempts: ${{ steps.retries.outputs.RETRIES }}
-#          retry_on: any
-#          warning_on_retry: true
-#          shell: bash
-#          continue_on_error: false
-#          on_retry_command: rm -f ${{ env.GLOBAL_DIR }}/*mercator*
-#          command: >-
-#            docker run \
-#              --rm \
-#              -v ${{ env.GLOBAL_DIR }}/:/tmp/somisana/current/ \
-#              -e COPERNICUS_USERNAME=${{ secrets.COPERNICUS_USERNAME }} \
-#              -e COPERNICUS_PASSWORD=${{ secrets.COPERNICUS_PASSWORD }} \
-#              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
-#                download \
-#                  --provider mercator \
-#                  --workdir /tmp/somisana/current \
-#                  --download-date ${{ env.MODEL_RUN_DATE }} \
-#                  --domain 22,31,-37,-31
+  toolkit:
+    needs: [envs]
+    runs-on: ubuntu-latest
+    env:
+      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
+      TOOLKIT_IMAGE: ${{ needs.envs.outputs.TOOLKIT_IMAGE }}
+      SHA: sha-${{ github.sha }}
+    outputs:
+      image: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.image_name }}
+    steps:
+      - name: Get image name lowercase
+        id: 'lowercase'
+        run: |
+          IMAGE_NAME_LOWER=$(echo $TOOLKIT_IMAGE | tr '[:upper:]' '[:lower:]')
+          echo "image_name=$IMAGE_NAME_LOWER" >> $GITHUB_OUTPUT
+      - name: Check out source code
+        uses: actions/checkout@master # change to main
+        with:
+          ref: ${{ env.BRANCH_REF }}
+      - name: Log in to the Container registry
+        uses: docker/login-action@master
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check if image with sha tag already exists
+        id: check-image
+        run: |
+          set -e
+          SHA_IMAGE=$(docker images -q ${REGISTRY}/${{ steps.lowercase.outputs.image_name }}:${SHA} || true)
+          if [ -z "$SHA_IMAGE" ]; then
+            echo "image_exists=false" >> $GITHUB_OUTPUT
+          else
+            echo "image_exists=true" >> $GITHUB_OUTPUT
+          fi
+      - name: Extract metadata (tags, labels) for Docker
+        id: meta
+        uses: docker/metadata-action@master
+        with:
+          images: ${{ env.REGISTRY }}/${{ env.TOOLKIT_IMAGE }}
+          tags: |
+            latest
+            ${{ env.SHA }}
+      - name: Build and push
+        uses: docker/build-push-action@master
+        with:
+          context: toolkit
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+
+  # Download environmental data used for model boundaries and surface forcing.
+  # This job is retried if it fails, since the failure can be due to upstream errors
+  # These downloads are used to create forcing files that are fed as input to the CROCO model
+  # => marine.copernicus.eu: This is ocean data that forms the lateral boundaries of our model run
+  # => ncei.noaa.gov: This is atmospheric data used to create surface boundary conditions for our model run
+  download-global-data:
+    needs: [toolkit, envs]
+    runs-on: somisana
+    env:
+      GLOBAL_DIR: ${{ needs.envs.outputs.GLOBAL_DIR }}
+      MODEL_RUN_DATE: ${{ needs.envs.outputs.MODEL_RUN_DATE }}
+      SHA: sha-${{ github.sha }}
+      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
+    steps:
+      - name: Clean /home/runner/somisana/global_data/ # haven't tested this part of the job yet!
+        run: >-
+          find \
+            /home/runner/somisana/global_data/* \
+            -maxdepth 0 \
+            -type d \
+            -ctime +5 \
+            -exec \
+              rm \
+                -rf {} \; 
+      - name: Configure no. retries
+        id: retries
+        run: |
+          if [ "$BRANCH_REF" = "stable" ]
+          then
+            echo "RETRIES=30" >> $GITHUB_OUTPUT
+          else
+            echo "RETRIES=1" >> $GITHUB_OUTPUT
+          fi
+      - name: Source ~/.bashrc (for NVM - required for non-interactive shells)
+        continue-on-error: true # Maybe Node.js exists anyway
+        run: |
+          source ~/.bashrc
+          nvm use 19.6.0
+      - name: Create ${{ env.GLOBAL_DIR }} directory 
+        run: |
+          rm -rf ${{ env.GLOBAL_DIR }} 
+          mkdir -p ${{ env.GLOBAL_DIR }} 
+          chown -R :runners ${{ env.GLOBAL_DIR }} 
+          chmod -R 774 ${{ env.GLOBAL_DIR }} 
+      - name: Download GFS # NOTE - DON"T WRITE TO /tmp IN THE IMAGE - RATHER USE /tmp/somisana/blah. Zach had --workdir /tmp/somisana/current/forcing-inputs - we don't have the forcing inputs directory. Not sure this impacts us now that we write the .env file to the same directory as where the global data are downloaded instead of above - need to check this still works with the matlab step
+        uses: nick-fields/retry@master 
+        with:
+          timeout_minutes: 30 # Script is considered failed if this limit is reached
+          retry_wait_seconds: 300 # Wait 5 minutes and try again
+          max_attempts: ${{ steps.retries.outputs.RETRIES }}
+          retry_on: any
+          warning_on_retry: true
+          shell: bash
+          continue_on_error: false
+          on_retry_command: rm -f ${{ env.GLOBAL_DIR }}/*grb*
+          command: >-
+            docker run \
+              --rm \
+              -v ${{ env.GLOBAL_DIR }}/:/tmp/somisana/current \
+              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
+                download \
+                  --provider gfs \
+                  --workdir /tmp/somisana/current \ 
+                  --matlab-env /tmp/somisana/current/.env \
+                  --download-date ${{ env.MODEL_RUN_DATE }} \
+                  --domain 22,31,-37,-31
+      - name: Download Mercator
+        uses: nick-fields/retry@master
+        with:
+          timeout_minutes: 30 # Script is considered failed if this limit is reached
+          retry_wait_seconds: 300 # Wait 5 minutes and try again
+          max_attempts: ${{ steps.retries.outputs.RETRIES }}
+          retry_on: any
+          warning_on_retry: true
+          shell: bash
+          continue_on_error: false
+          on_retry_command: rm -f ${{ env.GLOBAL_DIR }}/*mercator*
+          command: >-
+            docker run \
+              --rm \
+              -v ${{ env.GLOBAL_DIR }}/:/tmp/somisana/current/ \
+              -e COPERNICUS_USERNAME=${{ secrets.COPERNICUS_USERNAME }} \
+              -e COPERNICUS_PASSWORD=${{ secrets.COPERNICUS_PASSWORD }} \
+              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
+                download \
+                  --provider mercator \
+                  --workdir /tmp/somisana/current \
+                  --download-date ${{ env.MODEL_RUN_DATE }} \
+                  --domain 22,31,-37,-31
 
   call_run_algoa-bay-forecast:
     needs: [envs]
@@ -223,6 +223,7 @@ jobs:
       BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
       MODEL_RUN_DATE: ${{ needs.envs.outputs.MODEL_RUN_DATE }}
       RESTART_FILE_DATE: ${{ needs.envs.outputs.RESTART_FILE_DATE }} 
+      TOOLKIT_IMAGE: ${{ needs.envs.outputs.TOOLKIT_IMAGE }}
     secrets: inherit
 
 #  run_models:
