go back to begin, do not collect 00

diff --git a/.github/workflows/run_ops.yml b/.github/workflows/run_ops.yml
--- a/.github/workflows/run_ops.yml
+++ b/.github/workflows/run_ops.yml
@@ -70,139 +70,138 @@ jobs:
   # In the context of a testing environment, where updates to these
   # scripts is part of the development workflow, the toolkit needs
   # to be compiled on every run
-  toolkit:
-    needs: [envs]
-    runs-on: ubuntu-latest
-    env:
-      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
-      TOOLKIT_IMAGE: ${{ needs.envs.outputs.TOOLKIT_IMAGE }}
-      SHA: sha-${{ github.sha }}
-    outputs:
-      image: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.image_name }}
-    steps:
-      - name: Get image name lowercase
-        id: 'lowercase'
-        run: |
-          IMAGE_NAME_LOWER=$(echo $TOOLKIT_IMAGE | tr '[:upper:]' '[:lower:]')
-          echo "image_name=$IMAGE_NAME_LOWER" >> $GITHUB_OUTPUT
-      - name: Check out source code
-        uses: actions/checkout@master
-        with:
-          ref: ${{ env.BRANCH_REF }}
-      - name: Log in to the Container registry
-        uses: docker/login-action@master
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Check if image with sha tag already exists
-        id: check-image
-        run: |
-          set -e
-          SHA_IMAGE=$(docker images -q ${REGISTRY}/${{ steps.lowercase.outputs.image_name }}:${SHA} || true)
-          if [ -z "$SHA_IMAGE" ]; then
-            echo "image_exists=false" >> $GITHUB_OUTPUT
-          else
-            echo "image_exists=true" >> $GITHUB_OUTPUT
-          fi
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@master
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.TOOLKIT_IMAGE }}
-          tags: |
-            latest
-            ${{ env.SHA }}
-      - name: Build and push
-        uses: docker/build-push-action@master
-        with:
-          context: toolkit
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }
-  }
+#  toolkit:
+#    needs: [envs]
+#    runs-on: ubuntu-latest
+#    env:
+#      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
+#      TOOLKIT_IMAGE: ${{ needs.envs.outputs.TOOLKIT_IMAGE }}
+#      SHA: sha-${{ github.sha }}
+#    outputs:
+#      image: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.image_name }}
+#    steps:
+#      - name: Get image name lowercase
+#        id: 'lowercase'
+#        run: |
+#          IMAGE_NAME_LOWER=$(echo $TOOLKIT_IMAGE | tr '[:upper:]' '[:lower:]')
+#          echo "image_name=$IMAGE_NAME_LOWER" >> $GITHUB_OUTPUT
+#      - name: Check out source code
+#        uses: actions/checkout@master
+#        with:
+#          ref: ${{ env.BRANCH_REF }}
+#      - name: Log in to the Container registry
+#        uses: docker/login-action@master
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Check if image with sha tag already exists
+#        id: check-image
+#        run: |
+#          set -e
+#          SHA_IMAGE=$(docker images -q ${REGISTRY}/${{ steps.lowercase.outputs.image_name }}:${SHA} || true)
+#          if [ -z "$SHA_IMAGE" ]; then
+#            echo "image_exists=false" >> $GITHUB_OUTPUT
+#          else
+#            echo "image_exists=true" >> $GITHUB_OUTPUT
+#          fi
+#      - name: Extract metadata (tags, labels) for Docker
+#        id: meta
+#        uses: docker/metadata-action@master
+#        with:
+#          images: ${{ env.REGISTRY }}/${{ env.TOOLKIT_IMAGE }}
+#          tags: |
+#            latest
+#            ${{ env.SHA }}
+#      - name: Build and push
+#        uses: docker/build-push-action@master
+#        with:
+#          context: toolkit
+#          push: true
+#          tags: ${{ steps.meta.outputs.tags }}
+#          labels: ${{ steps.meta.outputs.labels }}
 
   # Download environmental data used to constrain model boundaries.
   # This job is retried if it fails, since the failure can be due to upstream errors
   # These downloads are used to create forcing files that are fed as input to the CROCO model
   # => marine.copernicus.eu: This is ocean data that forms the boundary of our model run
   # => ncei.noaa.gov: This is weather data used to create sea-surface conditions for our model run
-  boundary-data:
-    needs: [toolkit, envs]
-    runs-on: somisana
-    env:
-      GLOBAL_DIR: ${{ needs.envs.outputs.GLOBAL_DIR }}
-      MODEL_RUN_DATE: ${{ needs.envs.outputs.MODEL_RUN_DATE }}
-      SHA: sha-${{ github.sha }}
-      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
-    steps:
-      - name: Configure no. retries
-        id: retries
-        run: |
-          if [ "$BRANCH_REF" = "stable" ]
-          then
-            echo "RETRIES=30" >> $GITHUB_OUTPUT
-          else
-            echo "RETRIES=1" >> $GITHUB_OUTPUT
-          fi
-      - name: Source ~/.bashrc (for NVM - required for non-interactive shells)
-        continue-on-error: true # Maybe Node.js exists anyway
-        run: |
-          source ~/.bashrc
-          nvm use 19.6.0
-      - name: Create $GLOBAL_DIR directory 
-        run: |
-          rm -rf $GLOBAL_DIR 
-          mkdir -p $GLOBAL_DIR 
-          chown -R :runners $GLOBAL_DIR 
-          chmod -R 774 $GLOBAL_DIR 
-      - name: Download GFS
-        uses: nick-fields/retry@master
-        with:
-          timeout_minutes: 30 # Script is considered failed if this limit is reached
-          retry_wait_seconds: 300 # Wait 5 minutes and try again
-          max_attempts: ${{ steps.retries.outputs.RETRIES }}
-          retry_on: any
-          warning_on_retry: true
-          shell: bash
-          continue_on_error: false
-          on_retry_command: rm -f $GLOBAL_DIR/*grb*
-          command: >-
-            docker run \
-              --rm \
-              -v $GLOBAL_DIR/:/tmp/ \ 
-              -e COPERNICUS_USERNAME=${{ env.COPERNICUS_USERNAME }} \
-              -e COPERNICUS_PASSWORD=${{ env.COPERNICUS_PASSWORD }} \
-              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
-                download \
-                  --provider gfs \
-                  --workdir /tmp \
-                  --matlab-env /tmp/.env \
-                  --download-date ${{ env.MODEL_RUN_DATE }} \
-                  --domain 22,31,-37,-31
-      - name: Download Mercator
-        uses: nick-fields/retry@master
-        with:
-          timeout_minutes: 30 # Script is considered failed if this limit is reached
-          retry_wait_seconds: 300 # Wait 5 minutes and try again
-          max_attempts: ${{ steps.retries.outputs.RETRIES }}
-          retry_on: any
-          warning_on_retry: true
-          shell: bash
-          continue_on_error: false
-          on_retry_command: rm -f $GLOBAL_DIR/*mercator*
-          command: >-
-            docker run \
-              --rm \
-              -v $GLOBAL_DIR/:/tmp/ \
-              -e COPERNICUS_USERNAME=${{ env.COPERNICUS_USERNAME }} \
-              -e COPERNICUS_PASSWORD=${{ env.COPERNICUS_PASSWORD }} \
-              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
-                download \
-                  --provider mercator \
-                  --workdir /tmp \
-                  --download-date ${{ env.MODEL_RUN_DATE }} \
-                  --domain 22,31,-37,-31
+#  boundary-data:
+#    needs: [toolkit, envs]
+#    runs-on: somisana
+#    env:
+#      GLOBAL_DIR: ${{ needs.envs.outputs.GLOBAL_DIR }}
+#      MODEL_RUN_DATE: ${{ needs.envs.outputs.MODEL_RUN_DATE }}
+#      SHA: sha-${{ github.sha }}
+#      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
+#    steps:
+#      - name: Configure no. retries
+#        id: retries
+#        run: |
+#          if [ "$BRANCH_REF" = "stable" ]
+#          then
+#            echo "RETRIES=30" >> $GITHUB_OUTPUT
+#          else
+#            echo "RETRIES=1" >> $GITHUB_OUTPUT
+#          fi
+#      - name: Source ~/.bashrc (for NVM - required for non-interactive shells)
+#        continue-on-error: true # Maybe Node.js exists anyway
+#        run: |
+#          source ~/.bashrc
+#          nvm use 19.6.0
+#      - name: Create $GLOBAL_DIR directory 
+#        run: |
+#          rm -rf $GLOBAL_DIR 
+#          mkdir -p $GLOBAL_DIR 
+#          chown -R :runners $GLOBAL_DIR 
+#          chmod -R 774 $GLOBAL_DIR 
+#      - name: Download GFS
+#        uses: nick-fields/retry@master
+#        with:
+#          timeout_minutes: 30 # Script is considered failed if this limit is reached
+#          retry_wait_seconds: 300 # Wait 5 minutes and try again
+#          max_attempts: ${{ steps.retries.outputs.RETRIES }}
+#          retry_on: any
+#          warning_on_retry: true
+#          shell: bash
+#          continue_on_error: false
+#          on_retry_command: rm -f $GLOBAL_DIR/*grb*
+#          command: >-
+#            docker run \
+#              --rm \
+#              -v $GLOBAL_DIR/:/tmp/ \ 
+#              -e COPERNICUS_USERNAME=${{ env.COPERNICUS_USERNAME }} \
+#              -e COPERNICUS_PASSWORD=${{ env.COPERNICUS_PASSWORD }} \
+#              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
+#                download \
+#                  --provider gfs \
+#                  --workdir /tmp \
+#                  --matlab-env /tmp/.env \
+#                  --download-date ${{ env.MODEL_RUN_DATE }} \
+#                  --domain 22,31,-37,-31
+#      - name: Download Mercator
+#        uses: nick-fields/retry@master
+#        with:
+#          timeout_minutes: 30 # Script is considered failed if this limit is reached
+#          retry_wait_seconds: 300 # Wait 5 minutes and try again
+#          max_attempts: ${{ steps.retries.outputs.RETRIES }}
+#          retry_on: any
+#          warning_on_retry: true
+#          shell: bash
+#          continue_on_error: false
+#          on_retry_command: rm -f $GLOBAL_DIR/*mercator*
+#          command: >-
+#            docker run \
+#              --rm \
+#              -v $GLOBAL_DIR/:/tmp/ \
+#              -e COPERNICUS_USERNAME=${{ env.COPERNICUS_USERNAME }} \
+#              -e COPERNICUS_PASSWORD=${{ env.COPERNICUS_PASSWORD }} \
+#              ${{ needs.toolkit.outputs.image }}:${{ env.SHA }} \
+#                download \
+#                  --provider mercator \
+#                  --workdir /tmp \
+#                  --download-date ${{ env.MODEL_RUN_DATE }} \
+#                  --domain 22,31,-37,-31
 
   # Create a tmp folder structure for mode run assets. The format is:
   ## YYYYMMDD/
